name: ZZ Reusable
on:
  workflow_call:
    inputs:
      envname:
        type: string
        required: true
jobs:
  hi:
    runs-on: ubuntu-latest
    environment: ${{ inputs.envname }}
    steps:
      - run: echo "env=${{ inputs.envname }}"
